datasource.camunda.jdbc-url: jdbc:postgresql://localhost:5432/camunda
datasource.camunda.username: camunda
datasource.camunda.password: camunda
  
datasource.app.jdbc-url: jdbc:postgresql://localhost:5433/springboot
datasource.app.username: springboot
datasource.app.password: springboot

spring:
  jpa:
    hibernate:
      ddl-auto: create

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl:
    auto: update

camunda.bpm.admin-user:
  id: demo
  password: demo